defmodule SiwaServerWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :siwa_server

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :siwa_server,
    gzip: not code_reloading?,
    only: SiwaServerWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :siwa_server
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug SiwaServerWeb.JsonParser,
    parsers: [:json],
    pass: [],
    length: 65_536,
    read_length: 8_192,
    read_timeout: 5_000,
    json_decoder: Phoenix.json_library()

  plug Plug.Head
  plug SiwaServerWeb.Router
end
