import Config

pg_username = System.get_env("PGUSER") || System.get_env("USER") || "postgres"
pg_password = System.get_env("PGPASSWORD")
pg_hostname = System.get_env("PGHOST") || "localhost"
database_url = System.get_env("DATABASE_URL")

ssl_enabled =
  case database_url do
    value when is_binary(value) ->
      case URI.parse(value) do
        %URI{query: query} when is_binary(query) ->
          params = URI.decode_query(query)
          ssl = params["ssl"] |> to_string() |> String.trim() |> String.downcase()
          sslmode = params["sslmode"] |> to_string() |> String.trim() |> String.downcase()
          ssl in ~w(1 true yes on) or sslmode in ~w(require verify-ca verify-full)

        _other ->
          false
      end

    _other ->
      false
  end

# Configure your database
config :siwa_server,
       SiwaServer.Repo,
       if(is_binary(database_url) and String.trim(database_url) != "",
         do: [
           ssl: ssl_enabled,
           url: database_url,
           stacktrace: true,
           show_sensitive_data_on_connection_error: true,
           pool_size: 10
         ],
         else: [
           username: pg_username,
           password: pg_password,
           hostname: pg_hostname,
           database: "siwa_server_dev",
           stacktrace: true,
           show_sensitive_data_on_connection_error: true,
           pool_size: 10
         ]
       )

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :siwa_server, SiwaServerWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "CF6bAtHZYjx/y8Hl+X2vwmNT/RsHktt9fHvYTGoOjRd/E4J+M2z8stdNgBl/Ex8H",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :siwa_server, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
